<p style="color: #23262e;background-color: #ffffff;"><strong>Privacy Policy</strong></p>
<p style="color: #313642;background-color: #ffffff;">This privacy policy applies to the Event Countdown app for mobile devices, together with any related services operated by Uncle Deric Studios (collectively, the &quot;Application&quot;). Uncle Deric Studios is hereby referred to as the &quot;Service Provider&quot;.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Information Collection and Use</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Application collects information when you download and use it. This information may include information such as</p>
<ul style="list-style-type: disc;">
    <li style="color: #313642;background-color: #ffffff;">Your device&apos;s Internet Protocol address</li>
    <li style="color: #313642;background-color: #ffffff;">The pages of the Application that you visit, the time and date of your visit, the time spent on those pages</li>
    <li style="color: #313642;background-color: #ffffff;">The time spent on the Application</li>
    <li style="color: #313642;background-color: #ffffff;">your mobile operating system you use</li>
</ul>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Cookies and tracking technologies</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Application or its third-party SDKs may use cookies, SDKs, pixels, and similar technologies to support functionality, analytics, or service delivery. Where required by applicable law, the Service Provider will obtain consent before using non-essential tracking technologies.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Your Rights</strong></p>
<p style="color: #313642;background-color: #ffffff;">You may request access to, correction of, or deletion of your personal data held by the Service Provider. To exercise these rights, or to withdraw consent where processing is based on consent, contact the Service Provider at deric4eyes@icloud.com.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Your California privacy rights (CCPA/CPRA)</strong></p>
<p style="color: #313642;background-color: #ffffff;">If you are a California resident, you have the right to know what personal information is collected, the right to delete personal information, the right to opt out of the sale or sharing of personal information, and the right to non-discrimination for exercising these rights. To exercise your CCPA/CPRA rights, contact the Service Provider at deric4eyes@icloud.com.</p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider may use the information you provide to send important information, required notices, and, where permitted by law, marketing communications.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;">For a better experience while using the Application, the Service Provider may require you to provide certain personally identifiable information, including but not limited to none. The information the Service Provider requests will be retained and used as described in this privacy policy.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Third Party Access</strong></p>
<p style="color: #313642;background-color: #ffffff;">Only aggregated, anonymized data is periodically transmitted to external services to aid the Service Provider in improving the Application and their service. The Service Provider may share your information with third parties in the ways that are described in this privacy statement.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>International Data Transfers</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider or its third-party service providers may transfer personal data to countries outside your country of residence, including outside the European Economic Area (EEA). Where applicable law requires safeguards for international transfers, the Service Provider will use appropriate mechanisms.</p>
<ul style="list-style-type: disc;">
    <li style="color: #313642;background-color: #ffffff;">Standard Contractual Clauses (SCCs) approved by the European Commission</li>
    <li style="color: #313642;background-color: #ffffff;">Adequacy decisions or other legally recognized transfer mechanisms</li>
    <li style="color: #313642;background-color: #ffffff;">Your consent, where required and legally permitted</li>
</ul>
<p style="color: #313642;background-color: #ffffff;">Data protection laws in other countries may differ from those in your jurisdiction. Where required by law, the Service Provider will apply appropriate safeguards and obtain any consent required for the transfer.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider may disclose User Provided and Automatically Collected Information:</p>
<ul style="list-style-type: disc;">
    <li style="color: #313642;background-color: #ffffff;">as required by law, such as to comply with a subpoena, or similar legal process;</li>
    <li style="color: #313642;background-color: #ffffff;">when they believe in good faith that disclosure is necessary to protect their rights, protect your safety or the safety of others, investigate fraud, or respond to a government request;</li>
    <li style="color: #313642;background-color: #ffffff;">with their trusted services providers who work on their behalf, do not have an independent use of the information the Service Provider discloses to them, and have agreed to adhere to the rules set forth in this privacy statement.</li>
</ul>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Opt-Out Rights</strong></p>
<p style="color: #313642;background-color: #ffffff;">You can stop further collection of information from your mobile device by uninstalling the Application. Uninstalling will stop the Application from collecting data from your device, but it does not automatically delete information that has already been transmitted to the Service Provider or to third parties.</p>
<p style="color: #313642;background-color: #ffffff;">To request deletion of your personal data, to withdraw consent, or to exercise any of your rights, contact the Service Provider at deric4eyes@icloud.com.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Data Retention Policy</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider retains personal data based on its necessity for the stated purposes:</p>
<ul style="list-style-type: disc;">
    <li style="color: #313642;background-color: #ffffff;">User Provided Data: Retained for the duration of your use of the Application plus 12 months thereafter, unless longer retention is required by law</li>
    <li style="color: #313642;background-color: #ffffff;">Automatically Collected Data: Retained for up to 24 months from collection, unless longer retention is required for legal compliance</li>
    <li style="color: #313642;background-color: #ffffff;">Aggregated and Anonymized Data: Retained indefinitely as it no longer identifies you</li>
    <li style="color: #313642;background-color: #ffffff;">Data required for legal compliance: Retained as long as required by applicable law</li>
</ul>
<p style="color: #313642;background-color: #ffffff;">You may request deletion of your personal data, subject to any legal obligation to retain it. If you want the Service Provider to delete User Provided Data submitted through the Application, please contact them at deric4eyes@icloud.com. Please note that some User Provided Data may be required for the Application to function properly.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Children</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Application is not intended for children under 13 years of age, or such higher age as required by applicable law. The Service Provider does not knowingly solicit data from children or market the Application to them.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider does not knowingly collect personally identifiable information from children. The Service Provider encourages all children to never submit any personally identifiable information through the Application and/or Services. The Service Provider encourages parents and legal guardians to monitor their children&apos;s Internet usage and to help enforce this Policy by instructing their children never to provide personally identifiable information through the Application and/or Services without their permission. If you have reason to believe that a child has provided personally identifiable information to the Service Provider through the Application and/or Services, please contact the Service Provider so that they will be able to take the necessary actions. If you are under 13 years of age, your parent or guardian must provide consent on your behalf where permitted by law.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Security</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider is concerned about safeguarding the confidentiality of your information. The Service Provider provides physical, electronic, and procedural safeguards to protect information the Service Provider processes and maintains.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Data Breach Notification</strong></p>
<p style="color: #313642;background-color: #ffffff;">If a data breach occurs that affects your personal data, the Service Provider will notify you in accordance with applicable legal requirements, including, where required, providing information about the nature of the breach and the steps being taken to address it.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Changes</strong></p>
<p style="color: #313642;background-color: #ffffff;">The Service Provider may update this Privacy Policy from time to time. The Service Provider will notify you of material changes by posting the updated Privacy Policy with an effective date. Where required by law, the Service Provider will seek your consent to material changes before they take effect.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;">Previous versions of this Privacy Policy will be maintained and made available upon request by contacting the Service Provider at deric4eyes@icloud.com.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #313642;background-color: #ffffff;">This privacy policy is effective as of 2026-07-23</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Your Consent</strong></p>
<p style="color: #313642;background-color: #ffffff;">Where processing is based on consent, you provide that consent by affirmatively opting in to the relevant feature or action. You may withdraw consent at any time without affecting processing carried out before withdrawal. Processing based on other lawful bases is carried out as described above.</p>
<p style="color: #313642;background-color: #ffffff;"><br></p>
<p style="color: #23262e;background-color: #ffffff;"><strong>Contact Us</strong></p>
<p style="color: #313642;background-color: #ffffff;">If you have any questions regarding privacy while using the Application, or have questions about the practices, please contact the Service Provider via email at deric4eyes@icloud.com.</p>
<p style="color: #6d6d6d;background-color: #f0f1f4;"><br></p>
<p style="color: #313642;background-color: #ffffff;">This privacy policy page was generated by <a href="https://app-privacy-policy-generator.nisrulz.com/"><span style="color: #1e1fff;">App Privacy Policy Generator</span></a></p>
